package com.clearliang.frameworkdemo.model.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.clearliang.frameworkdemo.model.dao.OrderPay;

import com.clearliang.frameworkdemo.model.greendao.OrderPayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderPayDaoConfig;

    private final OrderPayDao orderPayDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderPayDaoConfig = daoConfigMap.get(OrderPayDao.class).clone();
        orderPayDaoConfig.initIdentityScope(type);

        orderPayDao = new OrderPayDao(orderPayDaoConfig, this);

        registerDao(OrderPay.class, orderPayDao);
    }
    
    public void clear() {
        orderPayDaoConfig.clearIdentityScope();
    }

    public OrderPayDao getOrderPayDao() {
        return orderPayDao;
    }

}
